blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://cortex-tms.org/
    about: Read the full documentation
  - name: Reddit Community
    url: https://reddit.com/r/cortextms
    about: Join the community discussion
